name: Build & Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Release Tag (e.g 2.3)"
        required: true
        type: string

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    permissions:
      contents: write

    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Cache Electron & deps
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/electron
            ~/.cache/electron-builder
            node_modules
          key: ${{ runner.os }}-electron-${{ hashFiles('package-lock.json') }}

      - name: Install deps
        run: npm ci

      - name: Set PUBLISH
        run: |
          echo "PUBLISH=onTagOrDraft" >> $GITHUB_ENV
          echo "RELEASE_VERSION=${{ inputs.tag }}" >> $GITHUB_ENV

      - name: Build Linux
        if: matrix.os == 'ubuntu-latest'
        run: npm run dist:linux

      - name: Build Windows
        if: matrix.os == 'windows-latest'
        run: npm run dist:win

      - name: Build macOS
        if: matrix.os == 'macos-latest'
        run: npm run dist:mac
